import 'package:supabase_flutter/supabase_flutter.dart';

/// Lets a second device adopt this device's account, via a short one-time
/// code exchanged through Postgres RPC
/// (`supabase/migrations/0003_device_pairing.sql`'s
/// `create_pairing_code()`/`redeem_pairing_code()`) - the only way around
/// `signInAnonymously()` otherwise minting a brand-new, disjoint identity
/// per install. No login/signup UI anywhere; this is the entire mechanism.
class PairingService {
  final SupabaseClient _client;

  PairingService(this._client);

  /// Generates a short code tied to this device's current session and
  /// stores it server-side for a few minutes. Show it to the user to type
  /// into the other device.
  Future<String> createPairingCode() async {
    final result = await _client.rpc('create_pairing_code');
    return result as String;
  }

  /// Redeems a code generated by another device and adopts that device's
  /// session, so this device becomes the same account going forward.
  /// Throws (surfaces the Postgres function's error message) if the code
  /// is invalid, expired, or already redeemed.
  Future<void> redeemPairingCode(String code) async {
    final refreshToken =
        await _client.rpc('redeem_pairing_code', params: {'p_code': code})
            as String;
    await _client.auth.setSession(refreshToken);
  }
}
